[simulation]
  name    = "16ppc"
  engine  = "srpic"
  runtime = 30.0

[grid]
  resolution = [4096, 4096]
  extent     = [[-2.048, 2.048], [-2.048, 2.048]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 0.1
  skindepth0 = 0.01

[algorithms]
  current_filters = 0

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 16.0

  [[particles.species]]
    label    = "e-_p"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 8e8

  [[particles.species]]
    label    = "e+_p"
    mass     = 20.0
    charge   = 1.0
    maxnpart = 8e8

  [[particles.species]]
    label    = "e-_b"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e1

  [[particles.species]]
    label    = "e+_b"
    mass     = 1.0
    charge   = 0.0
    maxnpart = 1e1

[setup]
  # Drift 4-velocities for each species in all 3 directions
  #   @type: array of floats (length = nspec)
  #   @default: [ 0.0, ... ]
  drifts_in_x = [0.0, 0.0]
  drifts_in_y = [0.0, 0.0]
  drifts_in_z = [0.0, 0.0]
  # Pair-wise species densities in units of n0
  #   @type: array of floats (length = nspec/2)
  #   @default: [ 2 / nspec, ... ]
  densities = [1.0]
  # Species temperatures in units of m0 (c^2)
  #   @type: array of floats (length = nspec)
  #   @default: [ 0.0, ... ]
  temperatures = [1e-2, 1e-2]
  # 
  # Single particle injection 
  x1_e  = [0.064]
  x2_e  = [0.256]
  x3_e  = [0.0]
  ux1_e = [10.0]
  ux2_e = [0.0]
  ux3_e = [0.0]

  x1_i  = [0.0]
  x2_i  = [0.0]
  x3_i  = [0.0]
  ux1_i = [0.0]
  ux2_i = [0.0]
  ux3_i = [0.0]

[output]
  format   = "BPFile"
  interval_time = 0.1

  [output.fields]
    enable = false
    quantities = ["N_1", "N_2", "E", "B", "J"]

  [output.particles]
    enable = true 
    species = [3]
    stride = 1

  [output.spectra]
    enable = false

[checkpoint]
  keep = 1

[diagnostics]
  log_level = "WARNING"
  blocking_timers = true